package app.funcarddeals.com.BeanClasses;

/**
 * Created by dx on 8/26/2015.
 */
public class FavouritesBeanClass {
    /**
     * variables for saving all favourites data.
     */

    private int FAVOURITES_ID;
    private String FAVOURITES_STORE_ID, FAVOURITES_STORE_NAME, FAVOURITES__STORE_LATITUDE, FAVOURITES_STORE_LONGITUDE, FAVOURITES_STORE_PRODUCT_ID, FAVOURITES_STORE_PRODUCT_NAME, FAVOURITES_STORE_PRODUCT_OFFER, FAVOURITES_STORE_PRODUCT_TIME;

    public int getFAVOURITES_ID() {
        return FAVOURITES_ID;
    }

    public void setFAVOURITES_ID(int FAVOURITES_ID) {
        this.FAVOURITES_ID = FAVOURITES_ID;
    }

    public String getFAVOURITES_STORE_ID() {
        return FAVOURITES_STORE_ID;
    }

    public void setFAVOURITES_STORE_ID(String FAVOURITES_STORE_ID) {
        this.FAVOURITES_STORE_ID = FAVOURITES_STORE_ID;
    }

    public String getFAVOURITES_STORE_NAME() {
        return FAVOURITES_STORE_NAME;
    }

    public void setFAVOURITES_STORE_NAME(String FAVOURITES_STORE_NAME) {
        this.FAVOURITES_STORE_NAME = FAVOURITES_STORE_NAME;
    }

    public String getFAVOURITES__STORE_LATITUDE() {
        return FAVOURITES__STORE_LATITUDE;
    }

    public void setFAVOURITES__STORE_LATITUDE(String FAVOURITES__STORE_LATITUDE) {
        this.FAVOURITES__STORE_LATITUDE = FAVOURITES__STORE_LATITUDE;
    }

    public String getFAVOURITES_STORE_LONGITUDE() {
        return FAVOURITES_STORE_LONGITUDE;
    }

    public void setFAVOURITES_STORE_LONGITUDE(String FAVOURITES_STORE_LONGITUDE) {
        this.FAVOURITES_STORE_LONGITUDE = FAVOURITES_STORE_LONGITUDE;
    }

    public String getFAVOURITES_STORE_PRODUCT_ID() {
        return FAVOURITES_STORE_PRODUCT_ID;
    }

    public void setFAVOURITES_STORE_PRODUCT_ID(String FAVOURITES_STORE_PRODUCT_ID) {
        this.FAVOURITES_STORE_PRODUCT_ID = FAVOURITES_STORE_PRODUCT_ID;
    }

    public String getFAVOURITES_STORE_PRODUCT_NAME() {
        return FAVOURITES_STORE_PRODUCT_NAME;
    }

    public void setFAVOURITES_STORE_PRODUCT_NAME(String FAVOURITES_STORE_PRODUCT_NAME) {
        this.FAVOURITES_STORE_PRODUCT_NAME = FAVOURITES_STORE_PRODUCT_NAME;
    }

    public String getFAVOURITES_STORE_PRODUCT_OFFER() {
        return FAVOURITES_STORE_PRODUCT_OFFER;
    }

    public void setFAVOURITES_STORE_PRODUCT_OFFER(String FAVOURITES_STORE_PRODUCT_OFFER) {
        this.FAVOURITES_STORE_PRODUCT_OFFER = FAVOURITES_STORE_PRODUCT_OFFER;
    }

    public String getFAVOURITES_STORE_PRODUCT_TIME() {
        return FAVOURITES_STORE_PRODUCT_TIME;
    }

    public void setFAVOURITES_STORE_PRODUCT_TIME(String FAVOURITES_STORE_PRODUCT_TIME) {
        this.FAVOURITES_STORE_PRODUCT_TIME = FAVOURITES_STORE_PRODUCT_TIME;
    }
}
